### ISSUE TITLE
 issue with simbol single quote

### ISSUE THREAD

**Issue by atanas-manoilov** [ivang/phoneticI#1]
macOS 10.13.3 High Sierra ( latest available MacOS )
Качил съм снимки от Keyboard Viewer. При натискане на символа '  ( показан на първия screenshot ) лейаута на клавиатурата се променя по начина показан на снимка 2. След натискане на който и да било клавиш, лейаута пак се връща в "нормален" режим.
Когато е натиснат shift този проблем го няма. Самия клавиш не е обозначен в жълто на Keyboard Viewer когато е натиснат шифт

![1](https://user-images.githubusercontent.com/3205449/37171508-6f2c7ba0-230e-11e8-8b75-4877c714b797.jpg)
![2](https://user-images.githubusercontent.com/3205449/37171509-6f4c9e6c-230e-11e8-91c1-619457bf0fe5.jpg)

ps. май по добре изцяло на английски да бях писал.. :)
поздрави!

**Comment by ivang** [comment]
Благодаря за съобщения проблем!

Това поведение на PhoneticI layout-а не ми беше известно, но се оказва, че и оригиналния layout, Bulgarian - Phonetic, има същото поведение. Освен това, `џ`, `ђ`, `њ`, `љ`, `ѓ`, `є`, `ї` и`ў` са все кирилишки букви. Първите пет се използват в сръбския и македонския, следващите два – в украинския, а последния – в беларуския. В този смисъл изглежда, че това не е bug, а е feature. :) Или пък, ако е bug, то той е у macOS, а не у PhoneticI... Което и от двете да е, затварям това issue.

PS. При това положение, за да се въведе `'`, трябва да се натисне интервал веднага след `'`.
